### Decision Tree Model:
The data has been split into two groups:
training set (train.csv)
test set (test.csv)
The training set is used to build your machine learning models. The training set provides the outcome (also known as the “ground truth”) for each passenger. Your model will be based on “features” like passengers’ gender and class. The test set is used to see how well your model performs on unseen data. The test set here does not provide the ground truth for each passenger. It is our job to predict these outcomes. For each passenger in the test set, use the model you trained to predict whether or not they survived the sinking of the Titanic.

In [1]:
# importing the libraries
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
# reading the csv file
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [3]:
train_data.head()
train_data.shape

(891, 12)

In [4]:
test_data.head()
test_data.shape

(418, 11)

In cell number 5
We have to select specific features that affect the values of the outcome. we can remove unwanted columns from the train and test dataset.

In [5]:
# removing the unwanted columns from training dataset with drop function
train_data = train_data.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket',
                              'Cabin', 'Embarked'], axis=1)
test_data = test_data.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket',
                            'Cabin', 'Embarked'], axis=1)

In [6]:
# we have removed the columns, now our data looks like this:
train_data.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [7]:
test_data.head()

   Pclass     Sex   Age     Fare
0       3    male  34.5   7.8292
1       3  female  47.0   7.0000
2       2    male  62.0   9.6875
3       3    male  27.0   8.6625
4       3  female  22.0  12.2875

in cell number 8
exploring the categorical columns by replacing the 0s for males and 1s for females. In the decision tree classification problem, we drop the labeled output data "Survived" from the main dataset and save it as x_train.

In [8]:
# exploring the categorical columns
x_train = train_data.drop('Survived', axis=1)
x_train.replace({'male':0, 'female':1}, inplace=True)
test_data.replace({'male':0, 'female':1},inplace=True)
y_train = train_data['Survived']
x_test = test_data.values
x_test

array([[ 3.    ,  0.    , 34.5   ,  7.8292],
       [ 3.    ,  1.    , 47.    ,  7.    ],
       [ 2.    ,  0.    , 62.    ,  9.6875],
       ...,
       [ 3.    ,  0.    , 38.5   ,  7.25  ],
       [ 3.    ,  0.    ,     nan,  8.05  ],
       [ 3.    ,  0.    ,     nan, 22.3583]])

In cell number 9
Sometimes our data contains null values. we have removed the null values before building the classifier model.

In [9]:
# checking for null values
x_train.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [10]:
# filling the missing values with mean of all values in column Age
x_train.Age = x_train.Age.fillna(x_train.Age.mean())
test_data.Age = test_data.Age.fillna(test_data.Age.mean())
test_data.Fare = test_data.Fare.fillna(test_data.Fare.mean())

In [11]:
# training the data with Decision Tree model
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [12]:
# prediction on the testing data
decision_tree.predict(test_data)

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])

Cell number 13:
The value of your Grid Search parameter could be a list that contains a Python dictionary. The key is the name of the parameter. The value of the dictionary is the different values of the parameter. This will make a table that can be viewed as various parameter values.
Different Outputs will be produced based on the different values of these parameters such as criterion as gini or entropy, max_depth as numbers from 1 to 10, and so on.

1. max_depth: Maximum depth of each tree

Controls the maximum number of levels a tree can grow.

Deeper trees → More complex model → Higher risk of overfitting.

Shallow trees → Simpler model → Lower risk of overfitting but may underfit.

Typical values:

None (default): The tree grows until all leaves are pure or reach min_samples_split.

Integer (e.g., max_depth=5): Limits the depth to prevent overfitting.

Tip:

For large datasets, use a smaller max_depth (e.g., 10–20).

For small datasets, you might leave it as None.

- 2. min_samples_leaf: Minimum number of samples required to be a leaf

Controls the minimum samples in the terminal nodes (leaves).

Helps prune the tree, making it less complex and reducing overfitting.

Higher values → Simpler, more generalized model.

Lower values → More complex model (higher risk of overfitting).

Typical values:

1 (default): Each leaf contains at least one sample.

5–10: For larger datasets, reduces overfitting.

50+: For very large datasets, further reduces complexity.

Tip:

Use higher values if you see overfitting.

- min_samples_split: controls the minimum number of samples required to split an internal node. It affects the tree's complexity and helps prevent overfitting.

In [13]:
# parameters for GridSearchCV
param_dict = {
    "criterion":['gini', 'entropy'],
    "max_depth":range(1,10),
    "min_samples_split":range(1,10),
    "min_samples_leaf":range(1,5)
}

Cell number 14:
create a GridSearchCV object. The inputs are the decision tree object, the parameter values, the number of folds which is 10 here.
- cross-validation (cv): It is used to calculate the score for each combination of parameters on the grid.
- verbose: controls the verbosity; the higher, the more messages. 
the parameter n_jobs is the number of jobs to run in parallel.
Then We train the model with the fit method.

In [14]:
# cross-validation (cv): It is used to
# calculate the score for each combination of parameters on the grid.
# verbose: controls the verbosity; the higher, the more messages.
grid = GridSearchCV(decision_tree,
                    param_grid=param_dict,
                    cv=10,
                    verbose=1,
                    n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 10 folds for each of 648 candidates, totalling 6480 fits

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(1, 10),
                         'min_samples_leaf': range(1, 5),
                         'min_samples_split': range(1, 10)},
             verbose=1)

Cell number 15 and 16
We find the best values for the parameters using the attribute best parameters or best estimator. advantages of Grid Search is how quickly we can test multiple parameters.

In [15]:
# the best values for the parameters
grid.best_params_

{'criterion': 'gini',
 'max_depth': 9,
 'min_samples_leaf': 3,
 'min_samples_split': 7}

In [16]:
grid.best_estimator_

DecisionTreeClassifier(max_depth=9, min_samples_leaf=3, min_samples_split=7)

Cell number 17 we find the best score.

In [17]:
grid.best_score_

0.8283520599250936